% Programming Fundamentals Using MATLAB, Michael Weeks Copyright 2020
% 
% program_9_3.m
    % See also getfilenameGUI_callback.m

    % 100 random integer values up to 50 
    mydata = round(50*rand(1,100));
    save mydata.mat
    clear 
    
    % Only need to do the above once.
    global fname
    global fighandle
    fighandle = figure();
    
    text_handle1 = uicontrol('Parent', fighandle, ...
       'Style', 'text', ...
       'String', 'Enter a filename', ...
       'Position', [30 70 100 20]);
       
    editText_handle = uicontrol('Parent', fighandle, ...
        'Style', 'edit', ...
        'String', '', ...
        'Position', [30 50 130 20], ...
        'Callback', {'getfilenameGUI_callback', 1});
        
    button_handle = uicontrol('Parent', fighandle, ...
        'Style', 'pushbutton', ...
        'String', 'Load', ...
        'Position', [300 10 100 100], ...
        'Callback', {'getfilenameGUI_callback', 2});
