apiVersion: v1
kind: Pod
metadata:
  name: sysctl-example
spec:
	securityContext:
		sysctls:
			- name: kernel.shm_rmid_forced
			value: "0"
			- name: net.core.somaxconn
			value: "10000"
			- name: kernel.msgmax
			value: "65536"
			- name: ipv4.ip_local_port_range
			value: ‘1024 65535’
