./ArrayAndPointer1
./ConcatenateStrings
./CountVowelsConsonants
./FindChar1
./ForLoopStr
./PointerArithmetic
./PointersNumbers1
./PointersNumbers2
./PointersStrings1
./PointersToNumbers1
./PrintCmdLineArguments
./SearchForWordInString
./SimplePointer1
./SimplePointer2
./SimplePointer3
./SimpleString
./Substrings
./Transpose
