    pump2 = PositiveDisplacement("Grumpy", 100, 0, 200, 300, 0.15)
    print("\n{} created.".format(pump2.name))
    print(pump2.get_speed_str())
    print(pump2.get_flow_str())
    print(pump2.get_power_str())
    pump2.adjust_speed(50)
    print(pump2.get_speed_str())
    print(pump2.get_flow_str())
    print(pump2.get_power_str())
    pump2.adjust_speed(0)
    print(pump2.get_speed_str())
    print(pump2.get_flow_str())
    print(pump2.get_power_str())
