% Programming Fundamentals Using MATLAB, Michael Weeks Copyright 2020
% 
%
% Demonstrate a button with an image.
% Also include a drop-down menu, and many other GUI elements.
% Most examples originate from MATLAB's help.
%
%

    % The variable "count" will be available globally,
    % that is, any other functions/script can access and change it. 
    global count;
    count = 23;  % Give it an initial value.
    disp(sprintf('count is initially set to %d', count));
    % Define the figure to use for our interface.
    figure_handle = figure(1);
    % Make the background color a deep green
    set(figure_handle, 'Color', [0.0 0.2 0.0]);
    % To see what other figure properties to change, try:
    % get(figure_handle)


    % Put two buttons in the figure.
    % Notice that we specify which figure by "figure_handle".
    % We do not have to specify 'Parent', but this helps readability.
    incButton_handle = uicontrol('Parent', figure_handle, ...
        'Style', 'pushbutton', ...
        'String', 'Inc count', ...
        'Position', [430 30 60 60], 'Callback', 'GUI_incCount');
    % Pushbutton seems to be the default.
    quitButton_handle = uicontrol('Parent', figure_handle, ...
        'Style', 'pushbutton', ...
        'String', 'Quit', ...
        'Position', [500 30 60 60], 'Callback', 'close'); 
    % Make the quit button a nice red. 
    set(quitButton_handle, 'BackgroundColor', [0.5 0 0]);
    % To see what other button properties to change, try:
    % get(quitButton_handle)


    % Show an image in the figure.
    x = imread('graphics/plant.jpg');
    % The axes function specifies where the image will go, and how
    % big it will be. The last two numbers after Position should be the
    % same size, since our image is square. 
    % Otherwise,we stretch the image.
    image_handle = axes('Parent', figure_handle, ...
        'Position', [.25 .4 .5 .5]);
    imshow(x);

    % Add a drop-down menu
    dropDownMenu_handle = uicontrol('Parent', figure_handle, ...
        'Style', 'popupmenu', ...
        'String', {'one','two','three','four'}, ...
        'Value', 1, 'Position', [50 80 100 20], ...
        'Callback', {'hello2', 'drop-down menu'});

    % Add a check box
    checkbox_handle = uicontrol('Parent', figure_handle, ...
        'Style', 'checkbox', ...
        'String', 'Check here please',...
        'Value', 0, 'Position', [30 20 130 20], ...
        'Callback', {'hello2', 'checkbox'});

    % Add change-able text
    editText_handle = uicontrol('Parent', figure_handle, ...
        'Style', 'edit', ...
        'String', 'Enter your name here.', ...
        'Position', [30 50 130 20], ...
        'Callback', {'hello2', 'editable text'});

    % Add text.
    text_handle1 = uicontrol('Parent', figure_handle, ...
        'Style', 'text', ...
        'String', 'Select a number from the menu below.', ...
        'Position', [30 100 130 40]);

    % Add toggle button.
    togglebutton_handle = uicontrol('Parent', figure_handle, ...
        'Style', 'togglebutton', ...
        'String', 'Toggle Me', ...
        'Value', 0, 'Position', [260 20 100 30], ...
        'Callback', {'hello2', 'toggle button'});

    % Add radio button.
    radiobutton_handle = uicontrol('Parent', figure_handle, ...
        'Style', 'radiobutton', ...
        'String', 'Radio button', ...
        'Value', 1, 'Position', [260 60 150 20], ...
        'Callback', {'hello2', 'radio button'});

    % Add slider.
    slider_handle = uicontrol('Parent', figure_handle, ...
        'Style', 'slider', ...
        'Max', 100, 'Min', 0, 'Value', 50, ...
        'SliderStep', [0.05 0.2], ...
        'Position', [260 80 150 30], ...
        'Callback', {'hello2', 'slider'});
    % Add text.
    text_handle2 = uicontrol('Parent', figure_handle, ...
        'Style', 'text', ...
        'String', 'Slide this left/right.', ...
        'Position', [260 110 130 20]);

    % Add a list box.
    listbox_handle = uicontrol('Parent', figure_handle, ...
        'Style', 'listbox', ...
        'String', {'alpha','beta','gamma','delta'}, ...
        'Value', 1, 'Position', [450 300 60 50], ...
        'Callback', {'hello2', 'list box'});

    % Add an option on the menu bar that calls "hello.m"
    % when selected.
    uimenu('Label', 'Hello', 'Callback', 'hello');

    % Give the user time to respond.
    disp('Select one through four');            
    pause(3);

    % Get the current value of the drop-down menu.
    v = get(dropDownMenu_handle, 'Value');           
    disp(sprintf('The drop-down menu has current value of %d.', v));


    disp('This script is terminating.');

