new_file = open("myfile.txt", "a")
new_file.write("Here's a new line.")
new_file.write("Here's another line.")
new_file.close()
read_file = open("myfile.txt")
read_file.readline()
newer_file = open("yourfile.txt", "w")
newer_file.write("This is a new file.\n")
newer_file.write("See how the lines are separate?\n")
newer_file.close()
read_file = open("yourfile.txt")
read_file.readlines()
print(read_file.readlines())
