x = 1

if x:  # if x is True...
    y = 2 # process this line
    if y:  # if y is True...
        print("x = true, y = true")  # process this line
    else:  # if y is False...
        print("x = true, y = false") # process this line
    print("x = true, y = unknown")  # if x is True, process this line
else:  # if x is False...
    print("x = false")  # process this line